//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kütüphane_modelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Islemler
    {
        public int Id { get; set; }
        public Nullable<int> UyeTc { get; set; }
        public Nullable<int> KitapNo { get; set; }
        public Nullable<System.DateTime> AlimTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
    
        public virtual Kitaplar Kitaplar { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
